title: Meu Repositório de Arquivos
description: Documentos, calculadoras e informações úteis.
logo: "/assets/sus-logo.png"
remote_theme: just-the-docs/just-the-docs
lang: pt-BR

# (Opcional) Ative a busca nativa do tema
just_the_docs:
  search_enabled: true